### ISSUE TITLE
Redirect URLs went missing 

### ISSUE THREAD

**Issue by Comat** [patrickdemooij9/SimpleRedirects#17]
Had a few URLs redirected but all the links are gone from view now. Tried adding new ones but it indicates " There was an error adding the redirect : An item with the same key has already been added"

**Comment by patrickdemooij9** [comment]
Hi Comat,

It sounds like there are duplicate urls in your redirects then. What version are you currently running?

Kind regards,
Patrick

**Comment by Comat** [comment]
Hi Patrick, I'm using Umbraco 8

**Comment by patrickdemooij9** [comment]
Hi Comat,

Sorry, I should have been more clear. Do you know what version is of the redirect manager you have?

**Comment by Comat** [comment]
I am using 1.0.8

**Comment by patrickdemooij9** [comment]
I'll take a look if the newest version fixes this issue later today and let you know!

**Comment by Comat** [comment]
Sure, thank you!

**Comment by patrickdemooij9** [comment]
Just checked it myself and it does indeed break when there are two same urls in the database. I'll see how I can prevent it from breaking and add that to the newest version.

I am just wondering how you managed to get a duplicate url in the database though. If I try to make a redirect with the same url, I'll get this error:
![image](https://user-images.githubusercontent.com/11466511/124884991-1a768300-dfd3-11eb-8221-eed50ddec546.png)

**Comment by Comat** [comment]
![image](https://user-images.githubusercontent.com/87053920/124885713-20398c00-e006-11eb-8eeb-860a5357b89f.png)

Trying to redirect a new path over when we shifted to a new URL paths with /# but not sure if that was the breaking point.
I could not create any redirects at all now nor view the past redirect URLs from platform now.

**Comment by patrickdemooij9** [comment]
Hi @Comat,

I just pushed version 1.0.11. There is a fix there for this issue. Could you check it out and see if it also fixes your issue?

**Comment by Comat** [comment]
![image](https://user-images.githubusercontent.com/87053920/125389996-ad992980-e3d4-11eb-8b0a-5a5d77817687.png)
Hi Patrick, the redirects that were previously created are still missing and I cannot do any redirect

**Comment by patrickdemooij9** [comment]
Hi @Comat,
I just double checked it and it seems like it's working for me. Could you try restarting the website to see if that has any effect?

If that doesn't work, can you answer the following questions?

1. How do you install the package? Are you installing it from Nuget.org or from the package section in Umbraco?
2. Are you still getting the same error in the logging viewer or is it a different one now?

**Comment by Comat** [comment]
![image](https://user-images.githubusercontent.com/87053920/125583824-27f6574b-dac7-4624-991a-f5c60d3e59e1.png)

Nothing is showing after restarting.

1. Installed from the package section in Umbraco.
2. Still the same error.

**Comment by patrickdemooij9** [comment]
@Comat, Hmmmm... That is very strange.
Can you confirm that you are on version 1.0.11 of SimpleRedirects? You can see that in the Installed tab at the packages section
![image](https://user-images.githubusercontent.com/11466511/125584386-7a8e08a9-3889-4d34-8fd6-277f62a0949f.png)

**Comment by Comat** [comment]
Hi Patrick, 

Oh yes, you are right. I have reinstalled the package and the redirect is working now.

**Comment by patrickdemooij9** [comment]
Hi @Comat,
That is great to hear! I'll now close the issue as it has been fixed.

**Comment by Comat** [comment]
Thank you!
